# Generated by Django 4.2.7 on 2023-12-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_rename_items_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-id']},
        ),
    ]
